LARGURA = 0
ALTURA = 0
LINHAS = 15
COLUNAS = 15
TEMPO_MOVIMENTO_IA = 300
TEMPO_PASSO_JOGADOR = 80
LARGURA_TILE = 56
ALTURA_TILE = 28

TITULO = "Labirinto Isométrico Aleatório v2"

FONTE_CAMINHO = "assets/fontes/HomeVideo.ttf"
TAMANHO_FONTE_PRINCIPAL = 48
TAMANHO_FONTE_SUB = 24