LARGURA = 0
ALTURA = 0
TAMANHO_GRID = 15
LINHAS = TAMANHO_GRID
COLUNAS = TAMANHO_GRID
TEMPO_MOVIMENTO_IA = 300
TEMPO_PASSO_JOGADOR = 80
LARGURA_TILE = 56
ALTURA_TILE = 28

TITULO = "Labirinto Isométrico Aleatório v2"

FONTE_CAMINHO = "assets/fontes/vhs-vcr-osd.ttf"
TAMANHO_FONTE_PRINCIPAL = 48
TAMANHO_FONTE_SUB = 24