"""Constantes de tempo do jogo (em milissegundos). Nenhum número mágico de
duração deve aparecer fora deste arquivo."""

TEMPO_MOVIMENTO_IA_INICIAL = 300
TEMPO_MOVIMENTO_IA_MINIMO = 30
TEMPO_PASSO_JOGADOR = 80
TEMPO_PASSO_JOGADOR_COM_POCAO = 40

DURACAO_POCAO_MS = 10_000
CONGELAMENTO_APOS_VORTEX_MS = 2_000

LIMITE_PROFUNDIDADE_LIMITADA_JOGO = 50
LIMITE_PROFUNDIDADE_LIMITADA_DEMONSTRATIVO = 3
